#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y update
sudo apt -y install haproxy
sudo ufw allow 80/tcp
sudo service haproxy start
config="\nfrontend alx_frontend\n\tbind *:80\n\tdefault_backend alx_backend\n"
config2="\nbackend alx_backend\n\tbalance roundrobin\n\tserver 475467-web-01 100.25.0.127:80 check\n\tserver 475467-web-02 107.23.161.15:80 check\n"
sudo sed -i "/504.http/ a\\${config}${config2}" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
