#!/usr/bin/env bash
# script that checks the connectivity of a host
#IP given as the first positional argument of the script

if [ -z "$1" ];
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
