#!/usr/bin/env bash
#script using while loop to display Best School 10 times

i=1
while [ $i -le 10 ]
do
    if [ $i == 9 ]
    then
       echo "Hi"
    else
	echo "Best School"
    fi
    ((i++))
done
